In [1]:
import numpy as np

In [2]:
customer= np.loadtxt("customer.csv", delimiter = ',',dtype = object)
customer = np.delete(customer,0,axis = 0)
print(customer)

[['cid-001' 'Customer_1' 'customer1@example.com' '+12345678901']
 ['cid-002' 'Customer_2' 'customer2@example.com' '+12345678902']
 ['cid-003' 'Customer_3' 'customer3@example.com' '+12345678903']
 ['cid-004' 'Customer_4' 'customer4@example.com' '+12345678904']
 ['cid-005' 'Customer_5' 'customer5@example.com' '+12345678905']
 ['cid-006' 'Customer_6' 'customer6@example.com' '+12345678906']
 ['cid-007' 'Customer_7' 'customer7@example.com' '+12345678907']
 ['cid-008' 'Customer_8' 'customer8@example.com' '+12345678908']
 ['cid-009' 'Customer_9' 'customer9@example.com' '+12345678909']
 ['cid-010' 'Customer_10' 'customer10@example.com' '+12345678910']
 ['cid-011' 'Customer_11' 'customer11@example.com' '+12345678911']
 ['cid-012' 'Customer_12' 'customer12@example.com' '+12345678912']
 ['cid-013' 'Customer_13' 'customer13@example.com' '+12345678913']
 ['cid-014' 'Customer_14' 'customer14@example.com' '+12345678914']
 ['cid-015' 'Customer_15' 'customer15@example.com' '+12345678915']
 ['cid-016' '

In [3]:
product = np.loadtxt("product.csv",delimiter = ',',dtype = str)
product = np.delete(product,0,axis = 0)
print(product)

[['pid-001' 'Product_1' '67.55']
 ['pid-002' 'Product_2' '12.25']
 ['pid-003' 'Product_3' '34.75']
 ['pid-004' 'Product_4' '30.09']
 ['pid-005' 'Product_5' '76.28']
 ['pid-006' 'Product_6' '70.9']
 ['pid-007' 'Product_7' '90.3']
 ['pid-008' 'Product_8' '17.82']
 ['pid-009' 'Product_9' '47.97']
 ['pid-010' 'Product_10' '12.68']
 ['pid-011' 'Product_11' '29.68']
 ['pid-012' 'Product_12' '55.48']
 ['pid-013' 'Product_13' '12.39']
 ['pid-014' 'Product_14' '27.9']
 ['pid-015' 'Product_15' '68.49']
 ['pid-016' 'Product_16' '59.04']
 ['pid-017' 'Product_17' '29.84']
 ['pid-018' 'Product_18' '63.03']
 ['pid-019' 'Product_19' '82.85']
 ['pid-020' 'Product_20' '10.58']]


Find how many customers are repeating on my store

In [41]:
order = np.loadtxt("order.csv",delimiter = ',',dtype = str)
np.set_printoptions(threshold = np.inf)
order = np.delete(order,0,axis = 0)
customer_id = order[:,1]
order_id = order[:,0]

unique_element,count = np.unique(customer_id,return_counts = True) 
customers_count = list(zip(unique_element,count))
repeated_cus = np.array([cust for (cust,count) in customers_count if count > 10])
customer_name = customer[:,1]


cust_name = [customer[np.where(customer == cst)[0],1] for cst in repeated_cus]
# c = [customer[np.where(customer == cst)[0],1] for cst in repeated_cus]
# print(c)
print(cust_name)
# print(customer_id)
# print(order_id)
# print(unique_element,count)
# print(customers_count)
print(repeated_cus)
# print(customer_name)

print(customer)

[array(['Customer_5'], dtype=object), array(['Customer_8'], dtype=object), array(['Customer_9'], dtype=object), array(['Customer_13'], dtype=object), array(['Customer_14'], dtype=object), array(['Customer_18'], dtype=object)]
[array(['Customer_5'], dtype=object), array(['Customer_8'], dtype=object), array(['Customer_9'], dtype=object), array(['Customer_13'], dtype=object), array(['Customer_14'], dtype=object), array(['Customer_18'], dtype=object)]
['cid-005' 'cid-008' 'cid-009' 'cid-013' 'cid-014' 'cid-018']
[['cid-001' 'Customer_1' 'customer1@example.com' '+12345678901']
 ['cid-002' 'Customer_2' 'customer2@example.com' '+12345678902']
 ['cid-003' 'Customer_3' 'customer3@example.com' '+12345678903']
 ['cid-004' 'Customer_4' 'customer4@example.com' '+12345678904']
 ['cid-005' 'Customer_5' 'customer5@example.com' '+12345678905']
 ['cid-006' 'Customer_6' 'customer6@example.com' '+12345678906']
 ['cid-007' 'Customer_7' 'customer7@example.com' '+12345678907']
 ['cid-008' 'Customer_8' 'custo

Find which product is top sailing product on the basis of repeated orders.

In [43]:
product_id = order[:,2]
# print(product_id)
best_products,count = np.unique(product_id,return_counts = True)
top_product = np.max(count)
print(top_product)
is_top = (count == top_product)
product_count = count[is_top]
best_products = best_products[is_top]
print(best_products,count)
print(is_top)
print(product_count)
print(best_products) 
print(product_count)
top_products = np.vstack((best_products, product_count)).T
print(top_products)
print(f"The top selling products are {best_products} with the count of{product_count}")

15
['pid-003' 'pid-019'] [ 6 10 15 12  7  5  7  9 13 10 13  8 12  8 14  5 12 13 15  6]
[False False  True False False False False False False False False False
 False False False False False False  True False]
[15 15]
['pid-003' 'pid-019']
[15 15]
[['pid-003' '15']
 ['pid-019' '15']]
The top selling products are ['pid-003' 'pid-019'] with the count of[15 15]


Find which product should be discontinued as it is the least soled product on my store

In [9]:
product_id = order[:,2]
print(np.sort(product_id))
not_unique_products,count = np.unique(product_id,return_counts = True)
not_unique_product = np.min(count)

is_min = (count == not_unique_product)
product_count = count[is_min]
not_unique_products = not_unique_products[is_min]
print(not_unique_products,count)
print(is_min)
print(not_unique_products) 
print(product_count)
least_products = np.vstack((not_unique_products, product_count)).T
print(least_products)
print(f"The product which should be discontinued are {not_unique_products} with the count of{product_count}")

['pid-001' 'pid-001' 'pid-001' 'pid-001' 'pid-001' 'pid-001' 'pid-002'
 'pid-002' 'pid-002' 'pid-002' 'pid-002' 'pid-002' 'pid-002' 'pid-002'
 'pid-002' 'pid-002' 'pid-003' 'pid-003' 'pid-003' 'pid-003' 'pid-003'
 'pid-003' 'pid-003' 'pid-003' 'pid-003' 'pid-003' 'pid-003' 'pid-003'
 'pid-003' 'pid-003' 'pid-003' 'pid-004' 'pid-004' 'pid-004' 'pid-004'
 'pid-004' 'pid-004' 'pid-004' 'pid-004' 'pid-004' 'pid-004' 'pid-004'
 'pid-004' 'pid-005' 'pid-005' 'pid-005' 'pid-005' 'pid-005' 'pid-005'
 'pid-005' 'pid-006' 'pid-006' 'pid-006' 'pid-006' 'pid-006' 'pid-007'
 'pid-007' 'pid-007' 'pid-007' 'pid-007' 'pid-007' 'pid-007' 'pid-008'
 'pid-008' 'pid-008' 'pid-008' 'pid-008' 'pid-008' 'pid-008' 'pid-008'
 'pid-008' 'pid-009' 'pid-009' 'pid-009' 'pid-009' 'pid-009' 'pid-009'
 'pid-009' 'pid-009' 'pid-009' 'pid-009' 'pid-009' 'pid-009' 'pid-009'
 'pid-010' 'pid-010' 'pid-010' 'pid-010' 'pid-010' 'pid-010' 'pid-010'
 'pid-010' 'pid-010' 'pid-010' 'pid-011' 'pid-011' 'pid-011' 'pid-011'
 'pid-

Find which customer should get more discount as he/she keep visiting my store more than 5 tines.

In [10]:
order = np.loadtxt("order.csv",delimiter = ',',dtype = str)
np.set_printoptions(threshold = np.inf)
order = np.delete(order,0,axis = 0)
customer_id = order[:,1]
order_id = order[:,0]

unique_element,count = np.unique(customer_id,return_counts = True) 

mask = count > 5

discount_customers = unique_element[mask]
order_count = count[mask]


sorted_indices = np.argsort(order_count)
sorted_customers = discount_customers[sorted_indices]
sorted_count = order_count[sorted_indices]

answer = np.column_stack((sorted_customers,sorted_count))

print(mask)
print(unique_element,count)
print(discount_customers)
print(order_count)
print(sorted_indices)
print(sorted_customers)
print(sorted_count)
print(answer)
print(f"These are some of the customers to which discount should be given {sorted_customers}")

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]
['cid-001' 'cid-002' 'cid-003' 'cid-004' 'cid-005' 'cid-006' 'cid-007'
 'cid-008' 'cid-009' 'cid-010' 'cid-011' 'cid-012' 'cid-013' 'cid-014'
 'cid-015' 'cid-016' 'cid-017' 'cid-018' 'cid-019' 'cid-020'] [ 8  8  8  9 12  9  9 16 17  6  9  9 11 12 10  9  8 17  6  7]
['cid-001' 'cid-002' 'cid-003' 'cid-004' 'cid-005' 'cid-006' 'cid-007'
 'cid-008' 'cid-009' 'cid-010' 'cid-011' 'cid-012' 'cid-013' 'cid-014'
 'cid-015' 'cid-016' 'cid-017' 'cid-018' 'cid-019' 'cid-020']
[ 8  8  8  9 12  9  9 16 17  6  9  9 11 12 10  9  8 17  6  7]
[ 9 18 19  0  2 16  1  5 11 15 10  3  6 14 12 13  4  7  8 17]
['cid-010' 'cid-019' 'cid-020' 'cid-001' 'cid-003' 'cid-017' 'cid-002'
 'cid-006' 'cid-012' 'cid-016' 'cid-011' 'cid-004' 'cid-007' 'cid-015'
 'cid-013' 'cid-014' 'cid-005' 'cid-008' 'cid-009' 'cid-018']
[ 6  6  7  8  8  8  8  9  9  9  9  9  9 10 11 12 12 16 17 17]
[['cid-010' '6']


What is my total income till end.

In [11]:
price_per_unit = order[:,4].astype(float)
quantity = order[:,3].astype(float)
total_income = np.sum(price_per_unit * quantity).astype(int)


print(price_per_unit)
print(quantity)
print(total_income)

print(f"Your total income till end is {total_income}")

[27.9  76.28 30.09 30.09 10.58 68.49 12.39 12.68 82.85 12.25 34.75 12.39
 55.48 55.48 34.75 63.03 68.49 63.03 12.25 29.68 34.75 29.68 12.39 47.97
 63.03 82.85 12.39 76.28 34.75 76.28 10.58 12.39 29.84 67.55 47.97 12.68
 68.49 29.84 30.09 10.58 55.48 29.84 29.68 30.09 17.82 82.85 59.04 76.28
 63.03 29.84 90.3  12.68 68.49 30.09 34.75 82.85 82.85 34.75 34.75 34.75
 47.97 63.03 82.85 59.04 30.09 55.48 68.49 12.25 30.09 90.3  76.28 47.97
 34.75 30.09 67.55 70.9  59.04 12.25 67.55 68.49 63.03 90.3  12.25 12.25
 12.25 29.84 12.25 70.9  34.75 30.09 82.85 10.58 82.85 29.68 29.68 12.39
 68.49 67.55 82.85 63.03 47.97 34.75 12.68 63.03 29.84 12.68 47.97 63.03
 12.68 29.68 29.84 12.25 47.97 29.68 70.9  27.9  30.09 63.03 82.85 27.9
 12.68 55.48 30.09 27.9  17.82 27.9  29.68 47.97 12.39 17.82 55.48 17.82
 12.39 34.75 29.84 29.68 47.97 47.97 10.58 29.68 29.84 82.85 12.25 29.84
 55.48 29.68 30.09 12.68 12.39 76.28 12.39 82.85 63.03 12.68 82.85 68.49
 90.3  70.9  29.84 34.75 17.82 67.55 59.04 68.49 90.

In [12]:
total_order = len(order_id)
average_order_value = total_income/total_order

print(total_order)
print(average_order_value)

200
128.02


Write me a full report on monthly sale.

In [14]:
report = f"""
===Monthly sales report===
Total revenue: ${total_income}
Total order:{total_order}
Average_Order_Value:{average_order_value}

---best selling Products---
{best_products}

---least selling products---
{not_unique_products}
"""
print(report)


===Monthly sales report===
Total revenue: $25604
Total order:200
Average_Order_Value:128.02

---best selling Products---
['pid-003' 'pid-019']

---least selling products---
['pid-006' 'pid-016']

