In [23]:
import numpy as np

In [24]:
arr_1 = np.arange(0,10)
arr_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr_2 = np.zeros(9).reshape(3,3)
arr_2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
arr_2 = np.ones(9).reshape(3,3)
arr_2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
arr_3 = np.linspace(0,5,10)
arr_3

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [28]:
my_array = np.array([10,20,30,40,50])
my_array2 = np.array([10,20,30,40,50])
print(my_array + my_array2)
print(my_array - my_array2)
print(my_array * my_array2)

[ 20  40  60  80 100]
[0 0 0 0 0]
[ 100  400  900 1600 2500]


In [29]:
my_array = np.array([10,20,30,40,50])
print(np.sum(my_array))
print(np.std(my_array))
print(np.max(my_array))
print(np.mean(my_array))

150
14.142135623730951
50
30.0


In [30]:
arr_3 = np.arange(1,13)
arr_3.eye(arr3,3)

AttributeError: 'numpy.ndarray' object has no attribute 'eye'