In [4]:
import numpy as np
from numpy import linalg as LA

In [5]:
arr_1 = np.array([[14,-7],[9,12]])
arr_2 = np.array([[6],[-9]])

print(arr_1)
print(arr_2)



# arr_5 = np.dot(LA.inv(arr_1),arr_2))


[[14 -7]
 [ 9 12]]
[[ 6]
 [-9]]


In [6]:
arr_3 = np.dot(arr_1,arr_2)
print(arr_3)

[[147]
 [-54]]


In [7]:
arr_4 = LA.matrix_power(arr_1,4)
print(arr_4)

[[-24899 -38948]
 [ 50076 -36027]]


In [8]:
arr_5 = LA.inv(arr_1)
print(arr_5)

[[ 0.05194805  0.03030303]
 [-0.03896104  0.06060606]]


In [9]:
arr_3 = np.array([[6,7],[8,9]])

print(arr_3)
print(arr_3)

result = np.dot(arr_3,arr_3)
print(result)

[[6 7]
 [8 9]]
[[6 7]
 [8 9]]
[[ 92 105]
 [120 137]]


In [10]:
# np.linalg.multi_dot()

arr_5 = np.array([[1, 2],
                  [3, 4]])

arr_6 = np.array([[2, 4],
                  [6, 9]])

ans = np.dot(arr_5,arr_6)


arr_7 = np.array([[5, 6],
                  [7, 8]])

print(arr_5)
print(arr_6)

print(ans)

print(arr_7)

[[1 2]
 [3 4]]
[[2 4]
 [6 9]]
[[14 22]
 [30 48]]
[[5 6]
 [7 8]]


In [12]:
result = LA.multi_dot((arr_5,arr_6,arr_7))

print(result)

[[224 260]
 [486 564]]


In [13]:
result = LA.det(arr_5)
print(result)

-2.0000000000000004


In [14]:
result = LA.matrix_power(arr_5,3)
print(result)

[[ 37  54]
 [ 81 118]]
