In [1]:
import numpy as np
from numpy import random

In [2]:
my_list = [1,2,3,4,5,6,7,8,55,54,56]
type(my_list)

list

In [7]:
np_array1 = np.random.randint(0,10, size = (10,10))
# np_array1 = np_array1*3
print(np_array1)

[[8 6 0 4 6 6 7 4 7 1]
 [6 8 4 1 2 6 3 8 0 2]
 [6 7 7 3 6 7 0 2 6 9]
 [4 6 0 8 3 3 7 9 9 2]
 [2 0 5 6 6 0 6 8 8 9]
 [7 1 7 7 7 8 8 1 4 9]
 [2 7 2 9 7 9 2 2 1 2]
 [5 6 6 8 9 0 5 4 6 2]
 [2 4 0 8 5 7 6 4 3 0]
 [8 6 7 5 4 3 5 7 8 7]]


In [4]:
np_array1[(np_array1%2 == 0)]

array([4, 8, 6, 8, 0, 6, 8, 2, 4, 4, 4, 8, 2, 4, 4, 2, 2, 8, 2, 6, 6, 4,
       8, 0, 8, 6, 8, 8, 2, 0, 4, 2, 4, 6, 0, 0, 4, 0, 2, 6, 0, 8, 0, 6,
       6, 0, 2, 2], dtype=int32)

In [5]:
np_array1[(np_array1%2 != 0)].size

52

In [6]:
np_array1.size

100