In [1]:
import numpy as np
import math

In [2]:
my_file = np.loadtxt("InvestmentDataset.csv", delimiter = ',',dtype = str)
features = my_file[0]
my_file = np.delete(my_file,0,axis = 0)
in_invest = 5000
add_investment = my_file[:,2].astype(float)

print(add_investment)
print(features)


roc = np.array([pro.replace("%","")for pro in my_file[:,1]]).astype(float)

loss_years = np.where(roc<0)
profit_years = np.where(roc>0)

Amean = np.mean(roc) * 100
roc = (roc/100) + 1
product = np.prod(roc)
Gmean = math.pow(product,1/len(roc))-1
iloc_AI = np.where(add_investment != 0)

print(len(roc))
print(roc)
print(my_file)
print(product)
print(Amean)
print(Gmean)
print(loss_years)
print(profit_years)
print(iloc_AI)

print(my_file[iloc_AI[0],3].astype(float) - add_investment[iloc_AI[0]])
print(f"Initial investment:{in_invest}")
print(f"Gmean:{Gmean*100}")
print(f"Amean:{Amean}")
print(f"Total Investment:{in_invest + np.sum(add_investment)}")
print(f"Loss making years{my_file[loss_years[0],0] + " years"}")
print(f"Profit making years{my_file[profit_years[0],0] + " years"}")

# my_file = np.loadtxt("InvestmentDataset.csv", delimiter = ',',dtype = str)
# features = my_file[0]
# in_invest = 5000
# print(features)
# my_file = np.delete(my_file,0, axis=0) #remove headers
# roc = np.array([pro.replace("%","") for pro in my_file[:,1]]).astype(float)
# add_invest =my_file[:,2].astype(float)
# print(add_invest)
# loss_years = np.where(roc<0)
# profit_years = np.where(roc>0) 
# amean = np.mean(roc/100)
# roc = (roc / 100)+1
# product = np.prod(roc)
# print(product)
# gmean = math.pow(product,1/len(roc)) - 1
# print(gmean)
# iloc_AI = np.where(add_invest != 0)

# print(my_file[iloc_AI[0],3].astype(float)-add_invest[iloc_AI[0]])
# print(f"GMean: {gmean*100}")
# print(f"AMean: {amean*100}")
# print(f"Total amount in bank: {my_file[-1,-1]}")
# print(f"Total investment: {in_invest +  np.sum (add_invest)}")
# print(f"loss making years : {my_file[loss_years[0],0]+'years'}")
# print(f"profit making years : {my_file[profit_years[0],0]+'years'}")

[   0.    0.    0.    0. 2000.    0.    0.    0.    0.    0.]
['Year' 'Profit Percentage' 'Additional Investment' 'Total Amount']
10
[1.25 0.7  1.22 1.28 1.25 1.05 0.75 1.3  0.78 1.28]
[['1' '25%' '0' '6250.00']
 ['2' '-30%' '0' '4375.00']
 ['3' '22%' '0' '5337.50']
 ['4' '28%' '0' '6832.00']
 ['5' '25%' '2000' '10840.00']
 ['6' '5%' '0' '11382.00']
 ['7' '-25%' '0' '8536.50']
 ['8' '30%' '0' '11097.45']
 ['9' '-22%' '0' '8656.01']
 ['10' '28%' '0' '11079.69']]
1.745767296
860.0
0.05730098145198537
(array([1, 6, 8]),)
(array([0, 2, 3, 4, 5, 7, 9]),)
(array([4]),)
[8840.]
Initial investment:5000
Gmean:5.730098145198537
Amean:860.0
Total Investment:7000.0
Loss making years['2 years' '7 years' '9 years']
Profit making years['1 years' '3 years' '4 years' '5 years' '6 years' '8 years' '10 years']


In [39]:
my_file = np.loadtxt("InvestmentDataset.csv", delimiter = ',',dtype = str)
features = my_file[0]
my_file = np.delete(my_file,0,axis = 0)
roc = np.array([pro.replace("%","")for pro in my_file[:,1]]).astype(float)
beginning_profit = roc[0:4]
ending_profit = roc[5:]

ending_value = np.array([my_file[4:5,3]]).astype(float)


cash_flow = np.array([my_file[4:5,2]]).astype(float)
beginning_value = np.array([my_file[3:4,3]]).astype(float)
spr = (ending_value - cash_flow)/beginning_value - 1
spr = (ending_value - cash_flow)/beginning_value - 1
spr = spr * 100
TWR = (beginning_profit * spr *ending_profit)-1

print(features)
print(my_file)
print(roc)
print(beginning_profit)
print(ending_profit)
print(cash_flow)
print(beginning_value)
print(ending_value )
print(spr)
print(TWR)



ValueError: operands could not be broadcast together with shapes (1,4) (5,) 