In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
myarray = np.array([[2],[4]])

In [4]:
print(np.shape(myarray))
print("rows:",np.shape(myarray)[0])
print("column:",np.shape(myarray)[1])

(2, 1)
rows: 2
column: 1


In [5]:
b = np.arange(0,200,10).reshape(4,5)

In [6]:
np.shape(b)

(4, 5)

In [7]:
print(b)

[[  0  10  20  30  40]
 [ 50  60  70  80  90]
 [100 110 120 130 140]
 [150 160 170 180 190]]


In [8]:
print(type(b))

<class 'numpy.ndarray'>


In [12]:
print(b[:3,:3])

[[  0  10  20]
 [ 50  60  70]
 [100 110 120]]


In [10]:
zeroarray = np.zeros((3,6),int)

In [11]:
zeroarray

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])